version: '3.4'
volumes: 
  pgadmin_data:
services: 
  pgadmin4:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGDB_PORT}:80
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy