FROM ubuntu:latest
MAINTAINER Etienne Trimaille <etienne@kartoza.com>

WORKDIR /home
RUN mkdir settings import_done import_queue base_pbf cache
VOLUME /home/settings /home/import_done /home/import_queue /home/base_pbf /home/cache

CMD True