name: build-image-latest
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  docker-builder:
    strategy:
      matrix:
        component:
          - imposm
          - osmupdate
          - osmenrich
    # Only push if PR happens in the same repo
    # if: github.event.pull_request.base.repo.url == github.event.pull_request.head.repo.url
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # We can't use Docker meta GitHub Action because
      # our tag name is unconventional
      # - name: Docker meta
      #   id: docker_meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ secrets.DOCKERHUB_REPO }}/docker-osm
      #     tags: |
      #       type=semver,pattern=\d.\d.\d
      #       type=ref,event=branch
      #       type=ref,event=pr

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker-${{ matrix.component }}
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/docker-osm:${{ matrix.component }}-latest
          cache-from: |
            type=gha,scope=prod
          cache-to: type=gha,scope=prod

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
